wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702387064.408679
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.8.10
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
